version: '3'
services:
  database:
    container_name: autoparts_postgres
    image: postgres:13
    environment:
      POSTGRES_DB: autoparts
      POSTGRES_USER: autoparts
      POSTGRES_PASSWORD: O9chs9VW3tHcgkTEV65wFYrl9r99AeWL
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5440:5432"